name: DonationBoardPlugin
main: se.fredsfursten.donationboardplugin.DonationBoardPlugin
version: 0.5-DEV
author: vanbrayne
description: A Minecraft plugin for keeping scores of donations on a donation board
commands:
  donationboard:
    description: Control the donation board
    usage: /donationboard shift | print | load | save | register
    permission-message: You don't have <permission>
permissions:
  donationboard.*:
    description: Gives access to all donationboard commands
    default: op
    donationboard.shift: true
    donationboard.print: true
    donationboard.load: true
    donationboard.save: true
    donationboard.register: true
  donationboard.shift:
    description: Access to /donationboard shift command
    default: op
  donationboard.print:
    description: Access to /donationboard print command
    default: op
  donationboard.load:
    description: Access to /donationboard load command
    default: op
  donationboard.save:
    description: Access to /donationboard save command
    default: op
  donationboard.perk:
    description: Access to /donationboard register command
    default: op
