name: DonationBoardPlugin
main: se.fredsfursten.donationboardplugin.DonationBoardPlugin
version: 0.4
author: vanbrayne
description: A Minecraft plugin for keeping scores of donations on a donation board
commands:
  donationboard:
    description: Control the donation board
    usage: /donationboard shift | print | promote | demote
    permission-message: You don't have <permission>
permissions:
  donationboard.*:
    description: Gives access to all donationboard commands
    default: op
    donationboard.shift: true
    donationboard.print: true
    donationboard.promote: true
    donationboard.demote: true
  donationboard.shift:
    description: Access to /donationboard shift command
    default: op
  donationboard.print:
    description: Access to /donationboard print command
    default: op
  donationboard.promote:
    description: Access to /donationboard promote command
    default: op
  donationboard.demote:
    description: Access to /donationboard demote command
    default: op
