name: DonationBoardPlugin
main: se.fredsfursten.donationboardplugin.DonationBoardPlugin
version: 1.4
author: vanbrayne
description: A Minecraft plugin for keeping scores of donations on a donation board
commands:
  donationboard:
    description: Control the donation board
    usage: /donationboard shift
    permission-message: You don't have <permission>
permissions:
  donationboard.*:
    description: Gives access to all donationboard commands
    default: op
    donationboard.shift: true
  donationboard.shift:
    description: Access to /donationboard shift command
    default: op

